### ISSUE TITLE
[US] Structure String.xml

### ISSUE THREAD

**Issue by KoglerT** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-android#53] opened 2023-03-27 17:59 UTC
# Description
As programmer, I want to havea structured String.xml> to see which string belongs to which component.

# Acceptance criteria
Structured String.xml for every component

**Comment by dev-Fabi** [comment] 2023-03-28 07:54
Duplicate of #54

**Closed** 2023-04-10 07:18 UTC
Labels: Android
